workflows:
  native-android:
    name: Jaga Mental
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      groups:
        - development
      vars:
        PACKAGE_NAME: "io.mindset.jagamental"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          ./gradlew bundleRelease -PversionCode=$($BUILD_NUMBER + 1) -PversionName=1.0.$BUILD_NUMBER
    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - galihputroaji.gh@gmail.com
#          - haldiespasya@gmail.com
#          - rahmahdiandian@gmail.com
#          - yoerdanatan@gmail.com
#          - aminfaruk.fa@gmail.com
#          - marcelavind61@gmail.com
        notify:
          success: true
          failure: false
#      google_play:
#        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
#        track: internal
#        submit_as_draft: true